name = "advent_of_code_julia"
uuid = "cf57ac94-96d3-4eb5-8b94-6304034ca09d"
version = "0.1.0"
authors = ["Eftychios Valeontis <valeontis@gmail.com>"]

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
Combinatorics = "1.0.3"
Dates = "1.11.0"
Plots = "1.41.2"
